package com.bugbuster.models;

public enum Role {
    DJ, MC, PHOTOGRAPHER, VIDEOGRAPHER, CATERER, TENTS_SUPPLIER, CHAIRS, FLORIST, BAKER, MIXOLOGIST,
    DRINKS_SUPPLIER, EVENT_DECORATOR, SECURITY_TEAM
}
